### Test GET all users
GET http://localhost:3000/api/comment
Accept: application/json

### Automated testing
GET http://localhost:3000/api/comment/test
Accept: application/json

### Test GET comment by id (get new comment id from database for each test)
GET http://localhost:3000/api/comment/6f810359-5790-4fc5-be36-d096a8e53f30
Accept: application/json


### Test DELETE comment by id (get new comment id from database for each test)
DELETE http://localhost:3000/api/comment/6f810359-5790-4fc5-be36-d096a8e53f30
Accept: application/json
