### Test GET all users
GET http://localhost:3000/api/statistics/likes
Accept: application/json

### Automated testing
GET http://localhost:3000/api/statistics/likes/test
Accept: application/json

### LikeList Test
GET   http://localhost:3000/api/statistics/likeList/
Accept: application/json

### Get Likes by User
GET http://localhost:3000/api/statistics/likesByUser/33333333-3333-3333-3333-333333333333
Accept: application/json




